name: bank_sampah
description: A store trash

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^10.0.0
  flutter_native_splash: ^2.3.1
  freezed_annotation: ^2.4.1
  firebase_storage: ^11.2.5
  path: ^1.8.3
  fpdart: ^0.6.0
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  image_cropper: ^5.0.0
  image_picker: ^1.0.1
  another_flushbar: ^1.12.30
  intl: ^0.18.1

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/logo.png'
  android: true
  ios: true
  web: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
