// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC6GldkLCZC9O1OrfEvqNNvrZu95YJLlk',
    appId: '1:938179980284:web:7295a61c064c76ae062079',
    messagingSenderId: '938179980284',
    projectId: 'banksampah-b3d01',
    authDomain: 'banksampah-b3d01.firebaseapp.com',
    storageBucket: 'banksampah-b3d01.appspot.com',
    measurementId: 'G-HXFHLY5K5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXJpqhDX8Uj3vZGzY26hJ4cxwMU6Zk4H0',
    appId: '1:938179980284:android:cece2402bf1dfb2e062079',
    messagingSenderId: '938179980284',
    projectId: 'banksampah-b3d01',
    storageBucket: 'banksampah-b3d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV5dZi3uFXiQ1o2b18VXhPSY7yOBD717g',
    appId: '1:938179980284:ios:31f5800cc5eeb188062079',
    messagingSenderId: '938179980284',
    projectId: 'banksampah-b3d01',
    storageBucket: 'banksampah-b3d01.appspot.com',
    iosClientId: '938179980284-lh5pbkvfamv41ikv59tj92o3266p957q.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankSampah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV5dZi3uFXiQ1o2b18VXhPSY7yOBD717g',
    appId: '1:938179980284:ios:9cc90de613eedd8b062079',
    messagingSenderId: '938179980284',
    projectId: 'banksampah-b3d01',
    storageBucket: 'banksampah-b3d01.appspot.com',
    iosClientId: '938179980284-6nb3mhvhuore3lj8d80gqc8teq2hv84g.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankSampah.RunnerTests',
  );
}
